name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pytest parameterized onnxruntime
        python -m pip install .
        # Require nightly for the corrected rotary embedding impl
        python -m pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
    - name: Test with pytest
      run: |
        pytest
